version: '3'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.13.4
    container_name: elasticsearch
    environment:
      - "discovery.type=single-node"
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200"
    volumes:
      - esdata:/usr/share/elasticsearch/data
    networks:
      - my-network

  logstash:
    image: docker.elastic.co/logstash/logstash:7.13.4
    container_name: logstash
    volumes:
      - ./logstash.conf:/usr/share/logstash/pipeline/logstash.conf
      - logs:/logs   # Mount the logs directory from the Spring Boot app image
    ports:
      - "5000:5000"
    depends_on:
      - elasticsearch
    networks:
      - my-network

  kibana:
    image: docker.elastic.co/kibana/kibana:7.13.4
    container_name: kibana
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    networks:
      - my-network

  springboot-app:
    image: iamgovindthakur/elk:1.0
    container_name: springboot-app
    ports:
      - "8080:8080"
    networks:
      - my-network

volumes:
  esdata:
  logs:  # Volume for logs from the Spring Boot app

networks:
  my-network:
